set terminal pdf enhanced font 'Times,12' size 4in,3in
set linetype 1 lc rgb "#E69F00" lw 2 pt 7
set linetype 2 lc rgb "#56B4E9" lw 2 pt 9
set linetype 3 lc rgb "#009E73" lw 2 pt 5
set linetype 4 lc rgb "#F0E442" lw 2 pt 11
set linetype 5 lc rgb "#0072B2" lw 2 pt 13
set linetype 6 lc rgb "#D55E00" lw 2 pt 6
set linetype 7 lc rgb "#CC79A7" lw 2 pt 8
set linetype 8 lc rgb "#000000" lw 2 pt 4
set grid
set xlabel 'x'
set pointsize 0.3
set output 'plot_density.pdf'
set ylabel 'Density'
plot 'outputs/two_wave/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'Two Wave', 'outputs/three_wave/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'Three Wave', 'outputs/modified_three_wave/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'Modified Three Wave', 'outputs/multi_point/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'Multi Point', 'outputs/multi_point_iso/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'Multi Point Iso', 'outputs/ZB_AR1D_LS/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB AR1D LS', 'outputs/ZB_AR1D_LSM/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB AR1D LSM', 'outputs/ZB_ARMD_LS/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMD LS', 'outputs/ZB_ARMD_LSM/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMD LSM', 'outputs/ZB_ARMDM_LS/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMDM LS', 'outputs/ZB_ARMDM_LSM/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMDM LSM', 'outputs/ZB_ARMDMAT_LS/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMDMAT LS', 'outputs/ZB_ARMDMAT_LSM/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMDMAT LSM', 'outputs/ZB_ARMDMMAT_LS/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMDMMAT LS', 'outputs/ZB_ARMDMMAT_LSM/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB ARMDMMAT LSM', 'outputs/ZB_AM_LS/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB AM LS', 'outputs/ZB_AM_LSM/output_-1.dat' using 1:9 smooth unique w lp lw 2 title 'ZB AM LSM'
set output 'plot_velocity.pdf'
set ylabel 'Velocity-X'
set key bottom left
plot 'outputs/two_wave/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'Two Wave', 'outputs/three_wave/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'Three Wave', 'outputs/modified_three_wave/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'Modified Three Wave', 'outputs/multi_point/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'Multi Point', 'outputs/multi_point_iso/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'Multi Point Iso', 'outputs/ZB_AR1D_LS/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB AR1D LS', 'outputs/ZB_AR1D_LSM/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB AR1D LSM', 'outputs/ZB_ARMD_LS/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMD LS', 'outputs/ZB_ARMD_LSM/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMD LSM', 'outputs/ZB_ARMDM_LS/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMDM LS', 'outputs/ZB_ARMDM_LSM/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMDM LSM', 'outputs/ZB_ARMDMAT_LS/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMDMAT LS', 'outputs/ZB_ARMDMAT_LSM/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMDMAT LSM', 'outputs/ZB_ARMDMMAT_LS/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMDMMAT LS', 'outputs/ZB_ARMDMMAT_LSM/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB ARMDMMAT LSM', 'outputs/ZB_AM_LS/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB AM LS', 'outputs/ZB_AM_LSM/output_-1.dat' using 1:10 smooth unique w lp lw 2 title 'ZB AM LSM'
set output 'plot_pressure.pdf'
set ylabel 'Pressure'
set key top right
plot 'outputs/two_wave/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'Two Wave', 'outputs/three_wave/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'Three Wave', 'outputs/modified_three_wave/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'Modified Three Wave', 'outputs/multi_point/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'Multi Point', 'outputs/multi_point_iso/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'Multi Point Iso', 'outputs/ZB_AR1D_LS/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB AR1D LS', 'outputs/ZB_AR1D_LSM/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB AR1D LSM', 'outputs/ZB_ARMD_LS/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMD LS', 'outputs/ZB_ARMD_LSM/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMD LSM', 'outputs/ZB_ARMDM_LS/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMDM LS', 'outputs/ZB_ARMDM_LSM/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMDM LSM', 'outputs/ZB_ARMDMAT_LS/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMDMAT LS', 'outputs/ZB_ARMDMAT_LSM/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMDMAT LSM', 'outputs/ZB_ARMDMMAT_LS/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMDMMAT LS', 'outputs/ZB_ARMDMMAT_LSM/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB ARMDMMAT LSM', 'outputs/ZB_AM_LS/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB AM LS', 'outputs/ZB_AM_LSM/output_-1.dat' using 1:13 smooth unique w lp lw 2 title 'ZB AM LSM'
ie(rho,p) = p/(rho*0.4)
set output 'plot_ie.pdf'
set ylabel 'Internal energy'
set key top left
plot 'outputs/two_wave/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'Two Wave', 'outputs/three_wave/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'Three Wave', 'outputs/modified_three_wave/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'Modified Three Wave', 'outputs/multi_point/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'Multi Point', 'outputs/multi_point_iso/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'Multi Point Iso', 'outputs/ZB_AR1D_LS/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB AR1D LS', 'outputs/ZB_AR1D_LSM/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB AR1D LSM', 'outputs/ZB_ARMD_LS/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMD LS', 'outputs/ZB_ARMD_LSM/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMD LSM', 'outputs/ZB_ARMDM_LS/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMDM LS', 'outputs/ZB_ARMDM_LSM/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMDM LSM', 'outputs/ZB_ARMDMAT_LS/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMDMAT LS', 'outputs/ZB_ARMDMAT_LSM/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMDMAT LSM', 'outputs/ZB_ARMDMMAT_LS/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMDMMAT LS', 'outputs/ZB_ARMDMMAT_LSM/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB ARMDMMAT LSM', 'outputs/ZB_AM_LS/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB AM LS', 'outputs/ZB_AM_LSM/output_-1.dat' using 1:(ie($9,$13)) smooth unique w lp lw 2 title 'ZB AM LSM'
